# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[(b'STARTED', b'Started'), (b'STOPED', b'Stoped'), (b'RESTARTING', b'Restarting'), (b'PENDING', b'Pending')], default=b'PENDING', max_length=25),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[(b'STARTED', b'Started'), (b'STOPED', b'Stoped'), (b'RESTARTING', b'Restarting'), (b'PENDING', b'Pending')], default=b'PENDING', max_length=25),
        ),
    ]
