# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20161228_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[(b'STARTED', b'Started'), (b'STOPPED', b'Stopped'), (b'RESTARTING', b'Restarting'), (b'RELOADING', b'Reloading'), (b'PENDING', b'Pending')], default=b'PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[(b'STARTED', b'Started'), (b'STOPPED', b'Stopped'), (b'RESTARTING', b'Restarting'), (b'RELOADING', b'Reloading'), (b'PENDING', b'Pending')], default=b'PENDING', max_length=25),
        ),
    ]
