# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20161229_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='execution',
            field=models.CharField(choices=[(b'PENDING', b'Pending'), (b'EXECUTING', b'Executing'), (b'EXECUTED', b'Executed'), (b'N_A', b'n/a')], default=b'N_A', max_length=25),
        ),
        migrations.AddField(
            model_name='service',
            name='execution',
            field=models.CharField(choices=[(b'PENDING', b'Pending'), (b'EXECUTING', b'Executing'), (b'EXECUTED', b'Executed'), (b'N_A', b'n/a')], default=b'N_A', max_length=25),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[(b'STARTING', b'Starting'), (b'STARTED', b'Started'), (b'STOPPING', b'Stopping'), (b'STOPPED', b'Stopped'), (b'RESTARTING', b'Restarting'), (b'RELOADING', b'Reloading'), (b'PENDING', b'Pending')], default=b'PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[(b'STARTING', b'Starting'), (b'STARTED', b'Started'), (b'STOPPING', b'Stopping'), (b'STOPPED', b'Stopped'), (b'RESTARTING', b'Restarting'), (b'RELOADING', b'Reloading'), (b'PENDING', b'Pending')], default=b'PENDING', max_length=25),
        ),
    ]
